#!/bin/bash

# Brief 앱 아이콘 생성 가이드

echo "🎨 Brief 앱 아이콘 생성 방법"
echo ""
echo "방법 1: SwiftUI Preview로 스크린샷 캡처"
echo "======================================"
echo ""
echo "1. Xcode에서 AppIconGenerator.swift 열기"
echo "2. Preview를 '아이콘 단독 - 풀 디자인' 또는 '미니멀'로 선택"
echo "3. Preview 창에서 아이콘 우클릭 → Export as Image"
echo "4. 또는 ⌘⇧4 (스크린샷)로 정확히 1024x1024 캡처"
echo ""
echo "방법 2: 스크립트로 자동 생성 (ImageMagick 필요)"
echo "=============================================="
echo ""

# ImageMagick 설치 확인
if ! command -v magick &> /dev/null && ! command -v convert &> /dev/null; then
    echo "⚠️  ImageMagick이 설치되어 있지 않습니다."
    echo ""
    echo "설치 방법:"
    echo "  brew install imagemagick"
    echo ""
    exit 1
fi

echo "✅ ImageMagick 설치됨"
echo ""
echo "참고: SwiftUI Preview에서 수동으로 내보내는 것을 권장합니다."
echo "      더 정확하고 아름다운 결과를 얻을 수 있습니다."
echo ""
echo "방법 3: Figma/Sketch로 디자인"
echo "=============================="
echo ""
echo "AppIconGenerator.swift의 디자인을 참고하여:"
echo "- 1024x1024 캔버스"
echo "- 배경: 다크 그라디언트 (#0A0A14 → #060612)"
echo "- 메인 링: 718px 원형, 122px 두께"
echo "- 그라디언트: 파랑(#5CB6FF) → 보라(#9466F2) → 핑크(#F2668E)"
echo "- 광택: 상단 30% 흰색 투명도"
echo ""
echo "macOS 아이콘 사이즈 (AppIcon.appiconset):"
echo "  - icon_16x16.png"
echo "  - icon_16x16@2x.png (32x32)"
echo "  - icon_32x32.png"
echo "  - icon_32x32@2x.png (64x64)"
echo "  - icon_128x128.png"
echo "  - icon_128x128@2x.png (256x256)"
echo "  - icon_256x256.png"
echo "  - icon_256x256@2x.png (512x512)"
echo "  - icon_512x512.png"
echo "  - icon_512x512@2x.png (1024x1024)"
echo ""
echo "Xcode Assets에 추가:"
echo "1. Assets.xcassets 열기"
echo "2. AppIcon 선택"
echo "3. 각 크기별 이미지를 드래그 앤 드롭"
echo ""
